### ISSUE TITLE
How to decrypt online,

### ISSUE THREAD

**Issue by ALAxHxC** [thenativeweb/crypto2#8]
Hi, im working with your project, at the moment works to decrypt and encrypt into node js, but for example if another server need decrypt, at the moment i cant make :(

My example:

```
global.password=process.env.SECRET || "D/YalX5i47K0G02X0vtyYJo2Z3A5q+A9";
var crypto2 = require('crypto2');
var password=String(global.password);
async function createPassword() {
    let new_password = await crypto2.createPassword();
    console.log(new_password);
}

async function encrypt(text){
const encrypted = await crypto2.encrypt(text,password );
console.log(encrypted)

}
async function decrypt(text){
const decrypted = await crypto2.decrypt(text, password);
console.log(decrypted)
}
createPassword();
encrypt("daniel");
encrypt("sha123");
decrypt("1e4288a599b19f4f1a6936550e8f60b1");
decrypt("72630a30f175a4264bef81af1410248f");

```

> 1e4288a599b19f4f1a6936550e8f60b1
> 72630a30f175a4264bef81af1410248f
> daniel
> sha123
> abFMTOKnOlNRo/QXsrDiBdLzErZSXxrd
> 

Works, but if i try into page like: 
http://www.cryptogrium.com/aes-encryption-online-ecb.html
or
http://www.devglan.com/online-tools/aes-encryption-decryption

Doesnt decrypt good , what i can do to test decrypt online :)
Thanks,

**Comment by goloroden** [comment]
Okay … here I am, back again 😉 

The problem was that we used the `crypto.createCipher` function internally, which *somehow* calculates an internal initialization vector. Since you didn't know this one, you couldn't provide it, and hence you couldn't decrypt your encrypted texts.

Anyway, the `crypto.createCipher` function is deprecated, so I replaced it with its modern version, `crypto.createCipheriv`. This changed the way you have to use `crypto2`, and hence led to a new major version, which is now out on npm (version 2.0.0).

To encrypt some text, do as follows:

```javascript
'use strict';

// Require crypto2, please note that it MUST be version 2.0.0
const crypto2 = require('crypto2');

(async () => {
  // Create a password from a secret key.
  const password = await crypto2.createPassword('secret');

  // Create a one-time valid initialization vector.
  const iv = await crypto2.createIv();

  // Encrypt your plain text, in this case 'the native web'.
  const encrypted = await crypto2.encrypt('the native web', password, iv);

  console.log(`Password: ${password}`);
  console.log(`Iv: ${iv}`);
  console.log(`Encrypted: ${encrypted}`);
})();
```

Do decrypt, you have to use the same `password` and `iv` again. Please note that you *have* to store both values. You cannot re-generate them, even if you know the original key for the password!

Now take those values, and go to http://www.devglan.com/online-tools/aes-encryption-decryption and enter the values there. Please also note to select `hex`, `CBC mode`, and `256 bit key length`. The result will then be encoded as Base64. If you then go to https://www.base64decode.org/ and decode the Base64 result, you will get back the initial value.

**Comment by ALAxHxC** [comment]
¡Oh! Muchas gracias, :) es por ayuda entre backend y la aplicación frontal :)

**Comment by goloroden** [comment]
You're welcome 😊
