### ISSUE TITLE
Create a keypair with a password?

### ISSUE THREAD

**Issue by eddiejibson** [thenativeweb/crypto2#9]
Hello, I've been using the function createKeyPair() but was wondering if there could be something implemented to allow the private key to be encrypted with a password? And then another function to verify a password against it?

**Comment by goloroden** [comment]
Hi @eddiejibson 😊 

Of course, it would be thinkable to integrate such a function: The reason we haven't done this so far is because we didn't need it - and most other libraries also can't handle it if a key is protected with a password.

Nevertheless, it would of course be feasible to implement it. As I said, we don't need it ourselves, but if you want to work on a pull request for it, we would be happy about it!

**Comment by abhijithvijayan** [comment]
@eddiejibson Did you find some package that does the private key encryption with a password?

**Comment by eddiejibson** [comment]
Unfortunately not, no. Let me know if you find anything, though.

27 Jun 2019, 08:27 by notifications@github.com:

**Comment by abhijithvijayan** [comment]
@eddiejibson https://github.com/digitalbazaar/forge/issues/686#issuecomment-506360606

I didn't test it out. See if this helps.
